from fastapi import APIRouter, Depends, HTTPException
from sqlmodel import Session, select
from app.db.session import get_session
from app.models.auth import User, Student, Company, UserRole
from app.schemas import UserCreate, UserPublic
from app.core.security import get_password_hash

router = APIRouter()

@router.post("/register", response_model=UserPublic)
def register_user(user_in: UserCreate, session: Session = Depends(get_session)):
    """
    Register a new user.
    1. Check if email exists.
    2. Hash password.
    3. Create User.
    4. Create associated Student/Company profile.
    """
    
    # 1. Check if email already exists
    statement = select(User).where(User.email == user_in.email)
    existing_user = session.exec(statement).first()
    if existing_user:
        raise HTTPException(status_code=400, detail="Email already registered")

    # 2. Create the User Object
    hashed_pwd = get_password_hash(user_in.password)
    new_user = User(
        email=user_in.email,
        password_hash=hashed_pwd,
        role=user_in.role
    )
    session.add(new_user)
    session.commit()
    session.refresh(new_user) # Get the ID generated by DB

    # 3. Create the Profile (Student or Company)
    if user_in.role == UserRole.STUDENT:
        new_profile = Student(
            user_id=new_user.id,
            full_name=user_in.full_name
        )
        session.add(new_profile)
    
    elif user_in.role == UserRole.COMPANY:
        new_profile = Company(
            user_id=new_user.id,
            company_name=user_in.full_name, # Using full_name as company name for now
            location="Not provided"
        )
        session.add(new_profile)

    session.commit()

    return new_user